[package]
name = "honeydew"
version = "0.1.0"
authors = ["Christopher Esterhuyse <christopher.esterhuyse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.4.0"
gfx_2020 = { path="../gfx_2020" }
gfx-backend-vulkan = "0.6.5"
ordered-float = "2.1.1"
bincode = "1.3.2"
serde = { version = "1.0.63", features = ["derive"] }
mio = {version="0.7.11", features = ["os-poll", "udp"] }