[package]
name = "honeydew"
version = "0.1.0"
authors = ["Christopher Esterhuyse <christopher.esterhuyse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.4.0"
gfx_2020 = { git = "https://github.com/sirkibsirkib/gfx_2020" }
ordered-float = "2.1.1"
bincode = "1.3.2"
ron = "0.6.4"
serde = { version = "1.0.63", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
gfx_backend = {package = "gfx-backend-vulkan", version = "0.6.5" }

[target.'cfg(macos)'.dependencies]
gfx_backend = {package = "gfx-backend-metal", version = "0.6.5" }


# gfx-backend-dx12 = "0.6.13"